In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
cols = ['loan_amnt', 'int_rate', 'installment']
data = pd.read_csv('data/lc_loan.csv', nrows = 30000, usecols = cols)

In [9]:
data.describe()

loan_amnt      int_rate   installment
count  30000.000000  30000.000000  30000.000000
mean   11625.541667     12.099109    323.002519
std     7805.452627      4.016570    209.120541
min     1000.000000      5.420000     19.870000
25%     5600.000000      8.880000    166.050000
50%    10000.000000     11.860000    280.000000
75%    15000.000000     15.200000    424.800000
max    35000.000000     24.590000   1305.190000

In [10]:
# standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

In [12]:
print(type(data_scaled))
print(data_scaled.mean(axis=0))
print(data_scaled.std(axis=0))

<class 'numpy.ndarray'>
[ 7.57912251e-17 -7.44648787e-16 -3.03164901e-17]
[1. 1. 1.]


In [13]:
print(cols)
print(data_scaled.min(axis=0))
print(data_scaled.max(axis=0))

['loan_amnt', 'int_rate', 'installment']
[-1.36132    -1.66291618 -1.44958295]
[2.99468193 3.10989181 4.69683105]


In [14]:
# normalization
# xnorm = (X - Xmin) / (Xmax - Xmin)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)

In [15]:
print(cols)
print(scaled.mean(axis=0))
print(scaled.std(axis=0))

['loan_amnt', 'int_rate', 'installment']
[0.31251593 0.34841464 0.23584206]
[0.22956831 0.20952027 0.16269649]


In [16]:
print(cols)
print(scaled.min(axis=0))
print(scaled.max(axis=0))

['loan_amnt', 'int_rate', 'installment']
[0. 0. 0.]
[1. 1. 1.]


In [20]:
# Robust scalar (scaling to median and quantiles)
# IQR = 75th quantile - 25th quantile
# X_scale = (X - X.median) / IGR

from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaled = scaler.fit_transform(data)

In [19]:
def print_stats(X):
    print(cols)
    print(X.mean(axis=0))
    print(X.std(axis=0))
    print(X.min(axis=0))
    print(X.max(axis=0))
    
print_stats(scaled)

['loan_amnt', 'int_rate', 'installment']
[0.17292996 0.03783365 0.16619331]
[0.83035346 0.6355227  0.80818186]
[-0.95744681 -1.01898734 -1.00533333]
[2.65957447 2.01424051 3.96208696]
