In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [20]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/Users/home/bin/anaconda3/envs/good/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [18]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, random_state=None, shuffle=False)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for x, y in kf.split(range(1, 10)):
    print(x, y)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model, X_train, X_test, y_train, y_test):
        model.fit(X_train, y_train)
        return model.score(X_test, y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [32]:
scores_l, scores_svm, scores_rf = [], [], []
for x_ind, y_ind in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[x_ind], digits.data[y_ind], digits.target[x_ind], digits.target[y_ind]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

/Users/home/bin/anaconda3/envs/good/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/home/bin/anaconda3/envs/good/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linea

In [34]:
from sklearn.model_selection import cross_val_score
for scores in (scores_l, scores_svm, scores_rf):
    print(np.average(scores))
    

0.9265442404006677
0.9677239844184752
0.9382303839732887


In [40]:
for i in range(90, 120, 3):
    print(i, np.average(cross_val_score(RandomForestClassifier(n_estimators=i), digits.data, digits.target)))

90 0.937137109254101
93 0.9326864747756114
96 0.9415800061900341
99 0.9360306406685236
102 0.9399117920148561
105 0.938248220365212
108 0.938248220365212
111 0.9404781801299906
114 0.9371417517796348
117 0.9332420303311668
