In [1]:
import numpy as np
streetlights = np.array( [ [ 1, 0, 1 ],
                            [ 0, 1, 1 ],
                            [ 0, 0, 1 ],
                            [ 1, 1, 1 ],
                            [ 0, 1, 1 ],
                            [ 1, 0, 1 ] ] )

In [2]:
walk_vs_stop = np.array( [ [ 0 ],
                           [ 1 ],
                           [ 0 ],
                           [ 1 ],
                           [ 1 ],
                           [ 0 ] ] )

In [8]:
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

input = streetlights[0]
goal_prediction = walk_vs_stop[0]
for _ in range(20):
    pred = input.dot(weights)
    error = (goal_prediction - pred) ** 2
    delta = pred - goal_prediction
    weights -= alpha * input * delta
    print('Error: ', error, ' Prediction: ', round(pred, 6))
    

Error:  [0.04]  Prediction:  -0.2
Error:  [0.0256]  Prediction:  -0.16
Error:  [0.016384]  Prediction:  -0.128
Error:  [0.01048576]  Prediction:  -0.1024
Error:  [0.00671089]  Prediction:  -0.08192
Error:  [0.00429497]  Prediction:  -0.065536
Error:  [0.00274878]  Prediction:  -0.052429
Error:  [0.00175922]  Prediction:  -0.041943
Error:  [0.0011259]  Prediction:  -0.033554
Error:  [0.00072058]  Prediction:  -0.026844
Error:  [0.00046117]  Prediction:  -0.021475
Error:  [0.00029515]  Prediction:  -0.01718
Error:  [0.00018889]  Prediction:  -0.013744
Error:  [0.00012089]  Prediction:  -0.010995
Error:  [7.73712525e-05]  Prediction:  -0.008796
Error:  [4.95176016e-05]  Prediction:  -0.007037
Error:  [3.1691265e-05]  Prediction:  -0.005629
Error:  [2.02824096e-05]  Prediction:  -0.004504
Error:  [1.29807421e-05]  Prediction:  -0.003603
Error:  [8.30767497e-06]  Prediction:  -0.002882


In [10]:
import numpy as np

a = np.array([0,1,2,1])
b = np.array([2,2,2,3])

print(a*b)             
print(a+b)             
print(a * 0.5)         
print(a + 0.5)         

[0 2 4 3]
[2 3 4 4]
[0.  0.5 1.  0.5]
[0.5 1.5 2.5 1.5]


##  Learning the whole dataset


In [13]:

for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:", round(prediction, 6))
        
    print('Iteration ', iteration, "Error:" + str(error_for_all_lights) + "\n")

Prediction: -0.000128
Prediction: 0.999888
Prediction: -0.000922
Prediction: 1.000833
Prediction: 0.999836
Prediction: -0.00015
Iteration  0 Error:[1.62172712e-06]

Prediction: -0.00012
Prediction: 0.999896
Prediction: -0.000859
Prediction: 1.000776
Prediction: 0.999847
Prediction: -0.000139
Iteration  1 Error:[1.40897298e-06]

Prediction: -0.000112
Prediction: 0.999903
Prediction: -0.000801
Prediction: 1.000724
Prediction: 0.999858
Prediction: -0.00013
Iteration  2 Error:[1.22413002e-06]

Prediction: -0.000104
Prediction: 0.99991
Prediction: -0.000746
Prediction: 1.000675
Prediction: 0.999867
Prediction: -0.000121
Iteration  3 Error:[1.06353659e-06]

Prediction: -9.7e-05
Prediction: 0.999916
Prediction: -0.000696
Prediction: 1.000629
Prediction: 0.999876
Prediction: -0.000113
Iteration  4 Error:[9.24011378e-07]

Prediction: -9e-05
Prediction: 0.999921
Prediction: -0.000649
Prediction: 1.000586
Prediction: 0.999885
Prediction: -0.000105
Iteration  5 Error:[8.02790462e-07]

Prediction: 

## Full, batch, and stochastic gradient descent


Stochastic gradient descent updates weights one example at a time

(Full) gradient descent updates weights one dataset at a time

Batch gradient descent updates weights after n examples (n in [8, 256])


## Edge case: Overfitting
The greatest challenge you’ll face with deep learning is convincing your neural network to generalize instead of just memorize. You’ll see this again. 

# DNN 

In [14]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)



In [16]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
   layer_2_error = 0
   for i in range(len(streetlights)):
      layer_0 = streetlights[i:i+1]
      layer_1 = relu(np.dot(layer_0,weights_0_1))
      layer_2 = np.dot(layer_1,weights_1_2)

      layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)

      layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
      # New code
      layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)

      weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
      weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

   if(iteration % 10 == 9):
      print("Error:" + str(layer_2_error))



Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05
